---

- name: Prepare
  tags: [always]
  ## 17/09/2026 - Exclude trixie, upstream repo serves a gitlab-ce package whose size mismatches its index
  hosts:
    - debian.bookworm
  tasks:
    - name: Apt
      ansible.builtin.import_role:
        name: manala.roles.apt
      vars:
        manala_apt_preferences:
          - gitlab-ce@gitlab-ce
