.SILENT:

##########
# Manala #
##########

include .manala/make/Makefile

########
# Role #
########

ROLE               = symfony_cli
ROLE_DISTRIBUTIONS = debian.jessie debian.stretch debian.buster
