#############
# Functions #
#############

ifeq ($(shell uname -s),Darwin)
define gitsplit
	docker run \
		--rm \
		--tty --interactive \
		--volume $(MANALA_CURRENT_DIR):/srv \
		--volume $(HOME)/.ssh:/root/.ssh \
		jderusse/gitsplit
endef
else
define gitsplit
	docker run \
		--rm \
		--tty --interactive \
		--volume $(MANALA_CURRENT_DIR):/srv \
		--volume $(SSH_AUTH_SOCK):/ssh-agent \
		--env SSH_AUTH_SOCK=/ssh-agent \
		jderusse/gitsplit
endef
endif
