#############
# Functions #
#############

ifeq ($(shell uname -s),Darwin)
define gitsplit
	docker run \
		--rm \
		--tty --interactive \
		--env GITSPLIT_GITHUB_API_TOKEN \
		--volume $(MANALA_CURRENT_DIR):/srv \
		jderusse/gitsplit
endef
else
define gitsplit
	docker run \
		--rm \
		--tty --interactive \
		--env GITSPLIT_GITHUB_API_TOKEN \
		--volume $(MANALA_CURRENT_DIR):/srv \
		jderusse/gitsplit
		--ref "${TRAVIS_BRANCH}"
endef
endif
