FROM {{ item.image }}

# Versions
ENV GOSS_VERSION=0.3.18

# System
RUN \
    apt-get update \
    && apt-get install --yes --no-install-recommends \
        curl ca-certificates \
        gnupg \
        procps \
        apt-transport-https \
        python3 python3-apt \
    # Bash
    && sed -i -e '/PS1=/s/\\h/\\H/' /etc/bash.bashrc \
    # Goss
    && curl -sSL https://github.com/aelsabbahy/goss/releases/download/v${GOSS_VERSION}/goss-linux-$(dpkg --print-architecture) \
        -o /usr/local/bin/goss \
    && chmod +x /usr/local/bin/goss
