FROM {{ item.image }}

# Versions
ENV GOSS_VERSION=0.4.2

ENV LC_ALL=C.UTF-8

# System
RUN \
    apt-get --quiet update \
    && apt-get --quiet --yes --purge --autoremove upgrade \
    && apt-get --quiet --yes --no-install-recommends --verbose-versions install \
        curl ca-certificates \
        gnupg \
        procps \
        apt-transport-https \
        python3 python3-apt \
    # Bash
    && sed -i -e '/PS1=/s/\\h/\\H/' /etc/bash.bashrc \
    # Goss
    && curl -sSL "https://github.com/aelsabbahy/goss/releases/download/v${GOSS_VERSION}/goss-linux-$(dpkg --print-architecture)" \
        --output /usr/local/bin/goss \
    && chmod +x /usr/local/bin/goss \
    # Clean
    && rm -rf /var/lib/apt/lists/*
