---

- name: Selections > Alternatives
  community.general.alternatives:
    name: "{{ item.selection }}"
    path: "{{ item.path }}"
    link: "{{ item.link | default(omit) }}"
  loop: "{{
    manala_alternatives_selections
      | flatten
      | manala.roles.staten(want='present')
  }}"
