---

- name: Update > Pull
  ansible.builtin.shell:  # noqa: risky-shell-pipe
    cmd: |
      docker image ls --format {% raw %}'{{.Repository}}:{{.Tag}}'{% endraw %} \
        | grep -v '<none>' \
        | xargs --max-lines=1 --no-run-if-empty docker pull
  changed_when: false
